[package]
name = "preview"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
headless_chrome = "0.9"
failure = "0.1"
image = "0.23"
actix-web = "3.3"
